name: dev_utils
description: "Collection of Widgets and helpful Methods that every developer needs."
version: 7.1.3
#homepage: https://bhoominn.github.io
repository: https://github.com/bhoominn/dev_utils
issue_tracker: https://github.com/bhoominn/dev_utils/issues
funding:
  - https://www.github.com/sponsors/bhoominn

environment:
  sdk: ^3.5.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.1.1
  plugin_platform_interface: ^2.1.8

  shared_preferences: ^2.5.2
  fluttertoast: ^8.2.12
  connectivity_plus: ^6.1.3
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.dev_utils
        pluginClass: DevUtilsPlugin
      ios:
        pluginClass: DevUtilsPlugin
      linux:
        pluginClass: DevUtilsPlugin
      macos:
        pluginClass: DevUtilsPlugin
      windows:
        pluginClass: DevUtilsPluginCApi
      web:
        pluginClass: NbUtilsWeb
        fileName: dev_utils_web.dart

  fonts:
    - family: LineAwesomeIcons
      fonts:
        - asset: fonts/LineAwesome.ttf
          weight: 400

  uses-material-design: true
  assets:
    - assets/icons/

topics:
  - widgets
  - extensions
  - utils
  - chatgpt
  - flutterutils
